version: "3.9"

services:
  tests:
    build:
      context: ..
      dockerfile: ci/Dockerfile
    volumes:
      - ../allure-results:/tests/allure-results
    command: pytest tests --alluredir=allure-results
