version: "3.9"

services:
  tests:
    build:
      context: ..
      dockerfile: ci/Dockerfile
    volumes:
      - ./allure-results:/tests/allure-results
    environment:
      PYTHONUNBUFFERED: 1
    command: pytest tests --alluredir=/tests/allure-results
